//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreApiPoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class login
    {
        public int LoginID { get; set; }
        public int CustomerID { get; set; }
        public string Password { get; set; }
        public Nullable<int> Status { get; set; }
        public string EmailID { get; set; }
    
        public virtual customer customer { get; set; }
    }
}
